package com.example.demo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.example.demo.model.Renjith;
import com.example.demo.repository.RenjithRepository;

@RestController

public class demoController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private RenjithRepository renjithRepository;
    
    @GetMapping(value = "/")
    public String getMessage() {
        return "Welcome home Renjith";
    }

    @GetMapping(value = "/test")
    public String getTestMessage() {
        return "Its test by Renjith";
    }

    @GetMapping(value="/add-detail") // Map ONLY GET Requests
    public @ResponseBody
    String addNewQuestion (@RequestParam String title
            , @RequestParam String description) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Renjith n = new Renjith();
        n.setTitle(title);
        n.setDescription(description);
        renjithRepository.save(n);
        return "Saved";
    }

    @GetMapping(value="/get-detail")
    public @ResponseBody Iterable<Renjith> getAllQuestions() {
        // This returns a JSON or XML with the questions
        return renjithRepository.findAll();
    }

}
